title: "COVID-19 Cough Research"
description: "COVID-19 screening using cough sound, fever and other vital information. "
site.url: coughresearch.github.io
site.github.url: https://github.com/coughresearch/
