title: "COVID-19 Cough Research"
description: "COVID-19 screening using cough sound, fever and other vital information. "
site.url: coughresearch.github.io
site.github.url: https://github.com/coughresearch/

collections:
  authors:
    output: true

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "my_author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
